from . import training_habilitation
from . import training_formation
from . import training_bloc
from . import training_module
from . import training_module_repartition
from . import training_week
from . import training_week_line
from . import training_document
from . import training_trainer
from . import training_inscription
from . import training_inscription_experience
from . import training_inscription_document
from . import training_alternance
from . import training_attendance
from . import training_formateur_jour
from . import training_formateur_semaine
from . import training_monthly_report
from . import training_certification
from . import training_jury_session
from . import training_certification_document
from . import training_expense
from . import training_depense_intervenant
from . import training_dropout
from . import training_otp
from . import training_convention
from . import res_partner_ext
from . import training_session
from . import training_survey